sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '14'
cache:
- node_modules
install:
- npm install
script:
  - npm run coverage
  - npm run test -- --browsers=Firefox
  - if [[ $TRAVIS_TEST_RESULT -eq 0 ]]; then cat coverage/*/lcov.info | ./node_modules/.bin/coveralls; fi
